[package]
name = "rgis-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "rgis"
path = "src/main.rs"

[dependencies]
rgis-core   = { path = "../rgis-core" }
rgis-io     = { path = "../rgis-io" }
rgis-render = { path = "../rgis-render" }
rgis-tiles  = { path = "../rgis-tiles" }

gpui        = { workspace = true }
tokio       = { workspace = true }
image       = { workspace = true }
